### ISSUE TITLE
Spool ID not displayed when selecting spool

### ISSUE THREAD

**Issue by Ohara2208** [mainsail-crew/mainsail#1675]
### Mainsail Version:

v2.8.0

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

When changing spool on web interface the Spool ID is not displayed.

### What did you expect to happen instead?

Spool ID to be Displayed

### How to reproduce this bug?

Change spool on the web interface and when the popup displaying your rolls comes up you will see the lack of Spool ID

### Additional information:

![image](https://github.com/mainsail-crew/mainsail/assets/149898595/3b31b13e-dace-4d4b-ba6d-24ff024ef081)

**Comment by meteyou** [comment]
this is already fixed: https://github.com/mainsail-crew/mainsail/pull/1605

**Comment by Ohara2208** [comment]
> this is already fixed: #1605

Has this been rolled out? Im on V2.8.0 and it still doesnt show. 
Spoolman 0.14.0

![image](https://github.com/mainsail-crew/mainsail/assets/149898595/bd40ac57-34b2-4047-a387-3679456b6ace)

**Comment by meteyou** [comment]
No sry... Next release will be in the next days.
